apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: laravel-cert
spec:
  secretName: laravel-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - laravel.angga-sr.xyz
