apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
type: Opaque
data:
  APP_KEY: "YmFzZTY0OkhsS1g1aFBKREx4LzZIeUY4bVpPeTNiZTNWdGE5R1JXOENsRTkzSjVsM2M9"
  DB_USERNAME: "YWRtaW5fdXNlcg=="
  DB_PASSWORD: "YWRtaW5fdXNlcmNja2tsbA=="
