controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      networking.gke.io/load-balancer-type: "External"
  config:
    use-http2: "true"
    use-forwarded-headers: "true"
    gzip: "on"
    gzip-types: "text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
